/* File generated by the BNF Converter (bnfc 2.9.4). */

//C++ Abstract Syntax Implementation.
#include <algorithm>
#include <string>
#include <vector>
#include "Absyn.H"

/********************   Program    ********************/
Program::Program(ListTopDef *p1)
{
  listtopdef_ = p1;

}

Program::Program(const Program & other)
{
  listtopdef_ = other.listtopdef_->clone();

}

Program &Program::operator=(const Program & other)
{
  Program tmp(other);
  swap(tmp);
  return *this;
}

void Program::swap(Program & other)
{
  std::swap(listtopdef_, other.listtopdef_);

}

Program::~Program()
{
  delete(listtopdef_);

}

void Program::accept(Visitor *v)
{
  v->visitProgram(this);
}

Program *Program::clone() const
{
  return new Program(*this);
}



/********************   Struct    ********************/
Struct::Struct(Ident p1, SBlk *p2)
{
  ident_ = p1;
  sblk_ = p2;

}

Struct::Struct(const Struct & other)
{
  ident_ = other.ident_;
  sblk_ = other.sblk_->clone();

}

Struct &Struct::operator=(const Struct & other)
{
  Struct tmp(other);
  swap(tmp);
  return *this;
}

void Struct::swap(Struct & other)
{
  std::swap(ident_, other.ident_);
  std::swap(sblk_, other.sblk_);

}

Struct::~Struct()
{
  delete(sblk_);

}

void Struct::accept(Visitor *v)
{
  v->visitStruct(this);
}

Struct *Struct::clone() const
{
  return new Struct(*this);
}



/********************   TypeDef    ********************/
TypeDef::TypeDef(Ident p1, Ident p2)
{
  ident_1 = p1;
  ident_2 = p2;

}

TypeDef::TypeDef(const TypeDef & other)
{
  ident_1 = other.ident_1;
  ident_2 = other.ident_2;

}

TypeDef &TypeDef::operator=(const TypeDef & other)
{
  TypeDef tmp(other);
  swap(tmp);
  return *this;
}

void TypeDef::swap(TypeDef & other)
{
  std::swap(ident_1, other.ident_1);
  std::swap(ident_2, other.ident_2);

}

TypeDef::~TypeDef()
{

}

void TypeDef::accept(Visitor *v)
{
  v->visitTypeDef(this);
}

TypeDef *TypeDef::clone() const
{
  return new TypeDef(*this);
}



/********************   TypeDefWS    ********************/
TypeDefWS::TypeDefWS(Ident p1, SBlk *p2, Ident p3)
{
  ident_1 = p1;
  sblk_ = p2;
  ident_2 = p3;

}

TypeDefWS::TypeDefWS(const TypeDefWS & other)
{
  ident_1 = other.ident_1;
  sblk_ = other.sblk_->clone();
  ident_2 = other.ident_2;

}

TypeDefWS &TypeDefWS::operator=(const TypeDefWS & other)
{
  TypeDefWS tmp(other);
  swap(tmp);
  return *this;
}

void TypeDefWS::swap(TypeDefWS & other)
{
  std::swap(ident_1, other.ident_1);
  std::swap(sblk_, other.sblk_);
  std::swap(ident_2, other.ident_2);

}

TypeDefWS::~TypeDefWS()
{
  delete(sblk_);

}

void TypeDefWS::accept(Visitor *v)
{
  v->visitTypeDefWS(this);
}

TypeDefWS *TypeDefWS::clone() const
{
  return new TypeDefWS(*this);
}



/********************   Enum    ********************/
Enum::Enum(Ident p1, ListEVal *p2)
{
  ident_ = p1;
  listeval_ = p2;

}

Enum::Enum(const Enum & other)
{
  ident_ = other.ident_;
  listeval_ = other.listeval_->clone();

}

Enum &Enum::operator=(const Enum & other)
{
  Enum tmp(other);
  swap(tmp);
  return *this;
}

void Enum::swap(Enum & other)
{
  std::swap(ident_, other.ident_);
  std::swap(listeval_, other.listeval_);

}

Enum::~Enum()
{
  delete(listeval_);

}

void Enum::accept(Visitor *v)
{
  v->visitEnum(this);
}

Enum *Enum::clone() const
{
  return new Enum(*this);
}



/********************   Class    ********************/
Class::Class(Ident p1, CBlk *p2)
{
  ident_ = p1;
  cblk_ = p2;

}

Class::Class(const Class & other)
{
  ident_ = other.ident_;
  cblk_ = other.cblk_->clone();

}

Class &Class::operator=(const Class & other)
{
  Class tmp(other);
  swap(tmp);
  return *this;
}

void Class::swap(Class & other)
{
  std::swap(ident_, other.ident_);
  std::swap(cblk_, other.cblk_);

}

Class::~Class()
{
  delete(cblk_);

}

void Class::accept(Visitor *v)
{
  v->visitClass(this);
}

Class *Class::clone() const
{
  return new Class(*this);
}



/********************   ClassWE    ********************/
ClassWE::ClassWE(Ident p1, Ident p2, CBlk *p3)
{
  ident_1 = p1;
  ident_2 = p2;
  cblk_ = p3;

}

ClassWE::ClassWE(const ClassWE & other)
{
  ident_1 = other.ident_1;
  ident_2 = other.ident_2;
  cblk_ = other.cblk_->clone();

}

ClassWE &ClassWE::operator=(const ClassWE & other)
{
  ClassWE tmp(other);
  swap(tmp);
  return *this;
}

void ClassWE::swap(ClassWE & other)
{
  std::swap(ident_1, other.ident_1);
  std::swap(ident_2, other.ident_2);
  std::swap(cblk_, other.cblk_);

}

ClassWE::~ClassWE()
{
  delete(cblk_);

}

void ClassWE::accept(Visitor *v)
{
  v->visitClassWE(this);
}

ClassWE *ClassWE::clone() const
{
  return new ClassWE(*this);
}



/********************   GFuncDef    ********************/
GFuncDef::GFuncDef(FnDef *p1)
{
  fndef_ = p1;

}

GFuncDef::GFuncDef(const GFuncDef & other)
{
  fndef_ = other.fndef_->clone();

}

GFuncDef &GFuncDef::operator=(const GFuncDef & other)
{
  GFuncDef tmp(other);
  swap(tmp);
  return *this;
}

void GFuncDef::swap(GFuncDef & other)
{
  std::swap(fndef_, other.fndef_);

}

GFuncDef::~GFuncDef()
{
  delete(fndef_);

}

void GFuncDef::accept(Visitor *v)
{
  v->visitGFuncDef(this);
}

GFuncDef *GFuncDef::clone() const
{
  return new GFuncDef(*this);
}



/********************   FuncDef    ********************/
FuncDef::FuncDef(Type *p1, Ident p2, ListArg *p3, Blk *p4)
{
  type_ = p1;
  ident_ = p2;
  listarg_ = p3;
  blk_ = p4;

}

FuncDef::FuncDef(const FuncDef & other)
{
  type_ = other.type_->clone();
  ident_ = other.ident_;
  listarg_ = other.listarg_->clone();
  blk_ = other.blk_->clone();

}

FuncDef &FuncDef::operator=(const FuncDef & other)
{
  FuncDef tmp(other);
  swap(tmp);
  return *this;
}

void FuncDef::swap(FuncDef & other)
{
  std::swap(type_, other.type_);
  std::swap(ident_, other.ident_);
  std::swap(listarg_, other.listarg_);
  std::swap(blk_, other.blk_);

}

FuncDef::~FuncDef()
{
  delete(type_);
  delete(listarg_);
  delete(blk_);

}

void FuncDef::accept(Visitor *v)
{
  v->visitFuncDef(this);
}

FuncDef *FuncDef::clone() const
{
  return new FuncDef(*this);
}



/********************   EnumValue    ********************/
EnumValue::EnumValue(Ident p1)
{
  ident_ = p1;

}

EnumValue::EnumValue(const EnumValue & other)
{
  ident_ = other.ident_;

}

EnumValue &EnumValue::operator=(const EnumValue & other)
{
  EnumValue tmp(other);
  swap(tmp);
  return *this;
}

void EnumValue::swap(EnumValue & other)
{
  std::swap(ident_, other.ident_);

}

EnumValue::~EnumValue()
{

}

void EnumValue::accept(Visitor *v)
{
  v->visitEnumValue(this);
}

EnumValue *EnumValue::clone() const
{
  return new EnumValue(*this);
}



/********************   Argument    ********************/
Argument::Argument(Type *p1, Ident p2)
{
  type_ = p1;
  ident_ = p2;

}

Argument::Argument(const Argument & other)
{
  type_ = other.type_->clone();
  ident_ = other.ident_;

}

Argument &Argument::operator=(const Argument & other)
{
  Argument tmp(other);
  swap(tmp);
  return *this;
}

void Argument::swap(Argument & other)
{
  std::swap(type_, other.type_);
  std::swap(ident_, other.ident_);

}

Argument::~Argument()
{
  delete(type_);

}

void Argument::accept(Visitor *v)
{
  v->visitArgument(this);
}

Argument *Argument::clone() const
{
  return new Argument(*this);
}



/********************   Int    ********************/
Int::Int()
{

}

Int::Int(const Int & other)
{

}

Int &Int::operator=(const Int & other)
{
  Int tmp(other);
  swap(tmp);
  return *this;
}

void Int::swap(Int & other)
{

}

Int::~Int()
{

}

void Int::accept(Visitor *v)
{
  v->visitInt(this);
}

Int *Int::clone() const
{
  return new Int(*this);
}



/********************   Doub    ********************/
Doub::Doub()
{

}

Doub::Doub(const Doub & other)
{

}

Doub &Doub::operator=(const Doub & other)
{
  Doub tmp(other);
  swap(tmp);
  return *this;
}

void Doub::swap(Doub & other)
{

}

Doub::~Doub()
{

}

void Doub::accept(Visitor *v)
{
  v->visitDoub(this);
}

Doub *Doub::clone() const
{
  return new Doub(*this);
}



/********************   Bool    ********************/
Bool::Bool()
{

}

Bool::Bool(const Bool & other)
{

}

Bool &Bool::operator=(const Bool & other)
{
  Bool tmp(other);
  swap(tmp);
  return *this;
}

void Bool::swap(Bool & other)
{

}

Bool::~Bool()
{

}

void Bool::accept(Visitor *v)
{
  v->visitBool(this);
}

Bool *Bool::clone() const
{
  return new Bool(*this);
}



/********************   Void    ********************/
Void::Void()
{

}

Void::Void(const Void & other)
{

}

Void &Void::operator=(const Void & other)
{
  Void tmp(other);
  swap(tmp);
  return *this;
}

void Void::swap(Void & other)
{

}

Void::~Void()
{

}

void Void::accept(Visitor *v)
{
  v->visitVoid(this);
}

Void *Void::clone() const
{
  return new Void(*this);
}



/********************   ObjT    ********************/
ObjT::ObjT(Ident p1)
{
  ident_ = p1;

}

ObjT::ObjT(const ObjT & other)
{
  ident_ = other.ident_;

}

ObjT &ObjT::operator=(const ObjT & other)
{
  ObjT tmp(other);
  swap(tmp);
  return *this;
}

void ObjT::swap(ObjT & other)
{
  std::swap(ident_, other.ident_);

}

ObjT::~ObjT()
{

}

void ObjT::accept(Visitor *v)
{
  v->visitObjT(this);
}

ObjT *ObjT::clone() const
{
  return new ObjT(*this);
}



/********************   Array    ********************/
Array::Array(Type *p1, BracketsOpt *p2)
{
  type_ = p1;
  bracketsopt_ = p2;

}

Array::Array(const Array & other)
{
  type_ = other.type_->clone();
  bracketsopt_ = other.bracketsopt_->clone();

}

Array &Array::operator=(const Array & other)
{
  Array tmp(other);
  swap(tmp);
  return *this;
}

void Array::swap(Array & other)
{
  std::swap(type_, other.type_);
  std::swap(bracketsopt_, other.bracketsopt_);

}

Array::~Array()
{
  delete(type_);
  delete(bracketsopt_);

}

void Array::accept(Visitor *v)
{
  v->visitArray(this);
}

Array *Array::clone() const
{
  return new Array(*this);
}



/********************   BracketsEmpty    ********************/
BracketsEmpty::BracketsEmpty()
{

}

BracketsEmpty::BracketsEmpty(const BracketsEmpty & other)
{

}

BracketsEmpty &BracketsEmpty::operator=(const BracketsEmpty & other)
{
  BracketsEmpty tmp(other);
  swap(tmp);
  return *this;
}

void BracketsEmpty::swap(BracketsEmpty & other)
{

}

BracketsEmpty::~BracketsEmpty()
{

}

void BracketsEmpty::accept(Visitor *v)
{
  v->visitBracketsEmpty(this);
}

BracketsEmpty *BracketsEmpty::clone() const
{
  return new BracketsEmpty(*this);
}



/********************   SBlock    ********************/
SBlock::SBlock(ListMemdef *p1)
{
  listmemdef_ = p1;

}

SBlock::SBlock(const SBlock & other)
{
  listmemdef_ = other.listmemdef_->clone();

}

SBlock &SBlock::operator=(const SBlock & other)
{
  SBlock tmp(other);
  swap(tmp);
  return *this;
}

void SBlock::swap(SBlock & other)
{
  std::swap(listmemdef_, other.listmemdef_);

}

SBlock::~SBlock()
{
  delete(listmemdef_);

}

void SBlock::accept(Visitor *v)
{
  v->visitSBlock(this);
}

SBlock *SBlock::clone() const
{
  return new SBlock(*this);
}



/********************   CBlock    ********************/
CBlock::CBlock(ListCMemdef *p1)
{
  listcmemdef_ = p1;

}

CBlock::CBlock(const CBlock & other)
{
  listcmemdef_ = other.listcmemdef_->clone();

}

CBlock &CBlock::operator=(const CBlock & other)
{
  CBlock tmp(other);
  swap(tmp);
  return *this;
}

void CBlock::swap(CBlock & other)
{
  std::swap(listcmemdef_, other.listcmemdef_);

}

CBlock::~CBlock()
{
  delete(listcmemdef_);

}

void CBlock::accept(Visitor *v)
{
  v->visitCBlock(this);
}

CBlock *CBlock::clone() const
{
  return new CBlock(*this);
}



/********************   MemberDef    ********************/
MemberDef::MemberDef(Type *p1, Ident p2)
{
  type_ = p1;
  ident_ = p2;

}

MemberDef::MemberDef(const MemberDef & other)
{
  type_ = other.type_->clone();
  ident_ = other.ident_;

}

MemberDef &MemberDef::operator=(const MemberDef & other)
{
  MemberDef tmp(other);
  swap(tmp);
  return *this;
}

void MemberDef::swap(MemberDef & other)
{
  std::swap(type_, other.type_);
  std::swap(ident_, other.ident_);

}

MemberDef::~MemberDef()
{
  delete(type_);

}

void MemberDef::accept(Visitor *v)
{
  v->visitMemberDef(this);
}

MemberDef *MemberDef::clone() const
{
  return new MemberDef(*this);
}



/********************   CVarDef    ********************/
CVarDef::CVarDef(Memdef *p1)
{
  memdef_ = p1;

}

CVarDef::CVarDef(const CVarDef & other)
{
  memdef_ = other.memdef_->clone();

}

CVarDef &CVarDef::operator=(const CVarDef & other)
{
  CVarDef tmp(other);
  swap(tmp);
  return *this;
}

void CVarDef::swap(CVarDef & other)
{
  std::swap(memdef_, other.memdef_);

}

CVarDef::~CVarDef()
{
  delete(memdef_);

}

void CVarDef::accept(Visitor *v)
{
  v->visitCVarDef(this);
}

CVarDef *CVarDef::clone() const
{
  return new CVarDef(*this);
}



/********************   CFuncDef    ********************/
CFuncDef::CFuncDef(FnDef *p1)
{
  fndef_ = p1;

}

CFuncDef::CFuncDef(const CFuncDef & other)
{
  fndef_ = other.fndef_->clone();

}

CFuncDef &CFuncDef::operator=(const CFuncDef & other)
{
  CFuncDef tmp(other);
  swap(tmp);
  return *this;
}

void CFuncDef::swap(CFuncDef & other)
{
  std::swap(fndef_, other.fndef_);

}

CFuncDef::~CFuncDef()
{
  delete(fndef_);

}

void CFuncDef::accept(Visitor *v)
{
  v->visitCFuncDef(this);
}

CFuncDef *CFuncDef::clone() const
{
  return new CFuncDef(*this);
}



/********************   Block    ********************/
Block::Block(ListStmt *p1)
{
  liststmt_ = p1;

}

Block::Block(const Block & other)
{
  liststmt_ = other.liststmt_->clone();

}

Block &Block::operator=(const Block & other)
{
  Block tmp(other);
  swap(tmp);
  return *this;
}

void Block::swap(Block & other)
{
  std::swap(liststmt_, other.liststmt_);

}

Block::~Block()
{
  delete(liststmt_);

}

void Block::accept(Visitor *v)
{
  v->visitBlock(this);
}

Block *Block::clone() const
{
  return new Block(*this);
}



/********************   Empty    ********************/
Empty::Empty()
{

}

Empty::Empty(const Empty & other)
{

}

Empty &Empty::operator=(const Empty & other)
{
  Empty tmp(other);
  swap(tmp);
  return *this;
}

void Empty::swap(Empty & other)
{

}

Empty::~Empty()
{

}

void Empty::accept(Visitor *v)
{
  v->visitEmpty(this);
}

Empty *Empty::clone() const
{
  return new Empty(*this);
}



/********************   BStmt    ********************/
BStmt::BStmt(Blk *p1)
{
  blk_ = p1;

}

BStmt::BStmt(const BStmt & other)
{
  blk_ = other.blk_->clone();

}

BStmt &BStmt::operator=(const BStmt & other)
{
  BStmt tmp(other);
  swap(tmp);
  return *this;
}

void BStmt::swap(BStmt & other)
{
  std::swap(blk_, other.blk_);

}

BStmt::~BStmt()
{
  delete(blk_);

}

void BStmt::accept(Visitor *v)
{
  v->visitBStmt(this);
}

BStmt *BStmt::clone() const
{
  return new BStmt(*this);
}



/********************   Decl    ********************/
Decl::Decl(Type *p1, ListItem *p2)
{
  type_ = p1;
  listitem_ = p2;

}

Decl::Decl(const Decl & other)
{
  type_ = other.type_->clone();
  listitem_ = other.listitem_->clone();

}

Decl &Decl::operator=(const Decl & other)
{
  Decl tmp(other);
  swap(tmp);
  return *this;
}

void Decl::swap(Decl & other)
{
  std::swap(type_, other.type_);
  std::swap(listitem_, other.listitem_);

}

Decl::~Decl()
{
  delete(type_);
  delete(listitem_);

}

void Decl::accept(Visitor *v)
{
  v->visitDecl(this);
}

Decl *Decl::clone() const
{
  return new Decl(*this);
}



/********************   NoInit    ********************/
NoInit::NoInit(Ident p1)
{
  ident_ = p1;

}

NoInit::NoInit(const NoInit & other)
{
  ident_ = other.ident_;

}

NoInit &NoInit::operator=(const NoInit & other)
{
  NoInit tmp(other);
  swap(tmp);
  return *this;
}

void NoInit::swap(NoInit & other)
{
  std::swap(ident_, other.ident_);

}

NoInit::~NoInit()
{

}

void NoInit::accept(Visitor *v)
{
  v->visitNoInit(this);
}

NoInit *NoInit::clone() const
{
  return new NoInit(*this);
}



/********************   Init    ********************/
Init::Init(Ident p1, Expr *p2)
{
  ident_ = p1;
  expr_ = p2;

}

Init::Init(const Init & other)
{
  ident_ = other.ident_;
  expr_ = other.expr_->clone();

}

Init &Init::operator=(const Init & other)
{
  Init tmp(other);
  swap(tmp);
  return *this;
}

void Init::swap(Init & other)
{
  std::swap(ident_, other.ident_);
  std::swap(expr_, other.expr_);

}

Init::~Init()
{
  delete(expr_);

}

void Init::accept(Visitor *v)
{
  v->visitInit(this);
}

Init *Init::clone() const
{
  return new Init(*this);
}



/********************   ELitInt    ********************/
ELitInt::ELitInt(Integer p1)
{
  integer_ = p1;

}

ELitInt::ELitInt(const ELitInt & other)
{
  integer_ = other.integer_;

}

ELitInt &ELitInt::operator=(const ELitInt & other)
{
  ELitInt tmp(other);
  swap(tmp);
  return *this;
}

void ELitInt::swap(ELitInt & other)
{
  std::swap(integer_, other.integer_);

}

ELitInt::~ELitInt()
{

}

void ELitInt::accept(Visitor *v)
{
  v->visitELitInt(this);
}

ELitInt *ELitInt::clone() const
{
  return new ELitInt(*this);
}



/********************   ELitDoub    ********************/
ELitDoub::ELitDoub(Double p1)
{
  double_ = p1;

}

ELitDoub::ELitDoub(const ELitDoub & other)
{
  double_ = other.double_;

}

ELitDoub &ELitDoub::operator=(const ELitDoub & other)
{
  ELitDoub tmp(other);
  swap(tmp);
  return *this;
}

void ELitDoub::swap(ELitDoub & other)
{
  std::swap(double_, other.double_);

}

ELitDoub::~ELitDoub()
{

}

void ELitDoub::accept(Visitor *v)
{
  v->visitELitDoub(this);
}

ELitDoub *ELitDoub::clone() const
{
  return new ELitDoub(*this);
}



/********************   ELitTrue    ********************/
ELitTrue::ELitTrue()
{

}

ELitTrue::ELitTrue(const ELitTrue & other)
{

}

ELitTrue &ELitTrue::operator=(const ELitTrue & other)
{
  ELitTrue tmp(other);
  swap(tmp);
  return *this;
}

void ELitTrue::swap(ELitTrue & other)
{

}

ELitTrue::~ELitTrue()
{

}

void ELitTrue::accept(Visitor *v)
{
  v->visitELitTrue(this);
}

ELitTrue *ELitTrue::clone() const
{
  return new ELitTrue(*this);
}



/********************   ELitFalse    ********************/
ELitFalse::ELitFalse()
{

}

ELitFalse::ELitFalse(const ELitFalse & other)
{

}

ELitFalse &ELitFalse::operator=(const ELitFalse & other)
{
  ELitFalse tmp(other);
  swap(tmp);
  return *this;
}

void ELitFalse::swap(ELitFalse & other)
{

}

ELitFalse::~ELitFalse()
{

}

void ELitFalse::accept(Visitor *v)
{
  v->visitELitFalse(this);
}

ELitFalse *ELitFalse::clone() const
{
  return new ELitFalse(*this);
}



/********************   EString    ********************/
EString::EString(String p1)
{
  string_ = p1;

}

EString::EString(const EString & other)
{
  string_ = other.string_;

}

EString &EString::operator=(const EString & other)
{
  EString tmp(other);
  swap(tmp);
  return *this;
}

void EString::swap(EString & other)
{
  std::swap(string_, other.string_);

}

EString::~EString()
{

}

void EString::accept(Visitor *v)
{
  v->visitEString(this);
}

EString *EString::clone() const
{
  return new EString(*this);
}



/********************   EVar    ********************/
EVar::EVar(Ident p1)
{
  ident_ = p1;

}

EVar::EVar(const EVar & other)
{
  ident_ = other.ident_;

}

EVar &EVar::operator=(const EVar & other)
{
  EVar tmp(other);
  swap(tmp);
  return *this;
}

void EVar::swap(EVar & other)
{
  std::swap(ident_, other.ident_);

}

EVar::~EVar()
{

}

void EVar::accept(Visitor *v)
{
  v->visitEVar(this);
}

EVar *EVar::clone() const
{
  return new EVar(*this);
}



/********************   EOr    ********************/
EOr::EOr(Expr *p1, Expr *p2)
{
  expr_1 = p1;
  expr_2 = p2;

}

EOr::EOr(const EOr & other)
{
  expr_1 = other.expr_1->clone();
  expr_2 = other.expr_2->clone();

}

EOr &EOr::operator=(const EOr & other)
{
  EOr tmp(other);
  swap(tmp);
  return *this;
}

void EOr::swap(EOr & other)
{
  std::swap(expr_1, other.expr_1);
  std::swap(expr_2, other.expr_2);

}

EOr::~EOr()
{
  delete(expr_1);
  delete(expr_2);

}

void EOr::accept(Visitor *v)
{
  v->visitEOr(this);
}

EOr *EOr::clone() const
{
  return new EOr(*this);
}




/********************   ListEVal    ********************/

void ListEVal::accept(Visitor *v)
{
  v->visitListEVal(this);
}

ListEVal *ListEVal::clone() const
{
  return new ListEVal(*this);
}

ListEVal* consListEVal(EVal* x, ListEVal* xs) {
  xs->insert(xs->begin(), x);
  return xs;
}


/********************   ListArg    ********************/

void ListArg::accept(Visitor *v)
{
  v->visitListArg(this);
}

ListArg *ListArg::clone() const
{
  return new ListArg(*this);
}

ListArg* consListArg(Arg* x, ListArg* xs) {
  xs->insert(xs->begin(), x);
  return xs;
}


/********************   ListTopDef    ********************/

void ListTopDef::accept(Visitor *v)
{
  v->visitListTopDef(this);
}

ListTopDef *ListTopDef::clone() const
{
  return new ListTopDef(*this);
}

ListTopDef* consListTopDef(TopDef* x, ListTopDef* xs) {
  xs->insert(xs->begin(), x);
  return xs;
}


/********************   ListBracketsOpt    ********************/

void ListBracketsOpt::accept(Visitor *v)
{
  v->visitListBracketsOpt(this);
}

ListBracketsOpt *ListBracketsOpt::clone() const
{
  return new ListBracketsOpt(*this);
}

ListBracketsOpt* consListBracketsOpt(BracketsOpt* x, ListBracketsOpt* xs) {
  xs->insert(xs->begin(), x);
  return xs;
}


/********************   ListType    ********************/

void ListType::accept(Visitor *v)
{
  v->visitListType(this);
}

ListType *ListType::clone() const
{
  return new ListType(*this);
}

ListType* consListType(Type* x, ListType* xs) {
  xs->insert(xs->begin(), x);
  return xs;
}


/********************   ListMemdef    ********************/

void ListMemdef::accept(Visitor *v)
{
  v->visitListMemdef(this);
}

ListMemdef *ListMemdef::clone() const
{
  return new ListMemdef(*this);
}

ListMemdef* consListMemdef(Memdef* x, ListMemdef* xs) {
  xs->insert(xs->begin(), x);
  return xs;
}


/********************   ListCMemdef    ********************/

void ListCMemdef::accept(Visitor *v)
{
  v->visitListCMemdef(this);
}

ListCMemdef *ListCMemdef::clone() const
{
  return new ListCMemdef(*this);
}

ListCMemdef* consListCMemdef(CMemdef* x, ListCMemdef* xs) {
  xs->insert(xs->begin(), x);
  return xs;
}


/********************   ListStmt    ********************/

void ListStmt::accept(Visitor *v)
{
  v->visitListStmt(this);
}

ListStmt *ListStmt::clone() const
{
  return new ListStmt(*this);
}

ListStmt* consListStmt(Stmt* x, ListStmt* xs) {
  xs->insert(xs->begin(), x);
  return xs;
}


/********************   ListItem    ********************/

void ListItem::accept(Visitor *v)
{
  v->visitListItem(this);
}

ListItem *ListItem::clone() const
{
  return new ListItem(*this);
}

ListItem* consListItem(Item* x, ListItem* xs) {
  xs->insert(xs->begin(), x);
  return xs;
}


/********************   ListExpr    ********************/

void ListExpr::accept(Visitor *v)
{
  v->visitListExpr(this);
}

ListExpr *ListExpr::clone() const
{
  return new ListExpr(*this);
}

ListExpr* consListExpr(Expr* x, ListExpr* xs) {
  xs->insert(xs->begin(), x);
  return xs;
}





