/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <string>
#include "Printer.H"
#define INDENT_WIDTH 2


//You may wish to change render
void PrintAbsyn::render(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppend(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppend('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppend(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ' ') bufAppend(c);
  else if (c == 0) return;
  else
  {
     bufAppend(c);
     bufAppend(' ');
  }
}

void PrintAbsyn::render(String s)
{
  render(s.c_str());
}

bool allIsSpace(const char *s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return false;
  return true;
}

void PrintAbsyn::render(const char *s)
{
  if (*s) /* C string not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppend(s);
    } else {
      bufAppend(s);
      bufAppend(' ');
    }
  }
}

void PrintAbsyn::indent()
{
  int n = _n_;
  while (--n >= 0)
    bufAppend(' ');
}

void PrintAbsyn::backup()
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void PrintAbsyn::removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppend('\n');
  indent();
}

PrintAbsyn::PrintAbsyn(void)
{
  _i_ = 0; _n_ = 0;
  buf_ = 0;
  bufReset();
}

PrintAbsyn::~PrintAbsyn(void)
{
}

char *PrintAbsyn::print(Visitable *v)
{
  _i_ = 0; _n_ = 0;
  bufReset();
  v->accept(this);
  return buf_;
}

void PrintAbsyn::visitProg(Prog *p) {} //abstract class

void PrintAbsyn::visitProgram(Program *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; visitListTopDef(p->listtopdef_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTopDef(TopDef *p) {} //abstract class

void PrintAbsyn::visitStruct(Struct *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("struct");
  visitIdent(p->ident_);
  _i_ = 0; p->sblk_->accept(this);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTypeDef(TypeDef *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("typedef");
  render("struct");
  visitIdent(p->ident_1);
  render('*');
  visitIdent(p->ident_2);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTypeDefWS(TypeDefWS *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("typedef");
  render("struct");
  visitIdent(p->ident_1);
  _i_ = 0; p->sblk_->accept(this);
  render('*');
  visitIdent(p->ident_2);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEnum(Enum *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("enum");
  visitIdent(p->ident_);
  render('{');
  _i_ = 0; visitListEVal(p->listeval_);
  render('}');
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitClass(Class *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("class");
  visitIdent(p->ident_);
  _i_ = 0; p->cblk_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitClassWE(ClassWE *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("class");
  visitIdent(p->ident_1);
  render("extends");
  visitIdent(p->ident_2);
  _i_ = 0; p->cblk_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitGFuncDef(GFuncDef *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->fndef_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFnDef(FnDef *p) {} //abstract class

void PrintAbsyn::visitFuncDef(FuncDef *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->type_->accept(this);
  visitIdent(p->ident_);
  render('(');
  _i_ = 0; visitListArg(p->listarg_);
  render(')');
  _i_ = 0; p->blk_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEVal(EVal *p) {} //abstract class

void PrintAbsyn::visitEnumValue(EnumValue *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListEVal(ListEVal *listeval)
{
  iterListEVal(listeval->begin(), listeval->end());
}

void PrintAbsyn::iterListEVal(ListEVal::const_iterator i, ListEVal::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListEVal(i+1, j);
  }
}

void PrintAbsyn::visitArg(Arg *p) {} //abstract class

void PrintAbsyn::visitArgument(Argument *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->type_->accept(this);
  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListArg(ListArg *listarg)
{
  iterListArg(listarg->begin(), listarg->end());
}

void PrintAbsyn::iterListArg(ListArg::const_iterator i, ListArg::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListArg(i+1, j);
  }
}

void PrintAbsyn::visitListTopDef(ListTopDef *listtopdef)
{
  iterListTopDef(listtopdef->begin(), listtopdef->end());
}

void PrintAbsyn::iterListTopDef(ListTopDef::const_iterator i, ListTopDef::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); iterListTopDef(i+1, j);
  }
}

void PrintAbsyn::visitType(Type *p) {} //abstract class

void PrintAbsyn::visitInt(Int *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("int");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDoub(Doub *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("double");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBool(Bool *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("boolean");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVoid(Void *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("void");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitObjT(ObjT *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArray(Array *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->type_->accept(this);
  _i_ = 0; p->bracketsopt_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBracketsOpt(BracketsOpt *p) {} //abstract class

void PrintAbsyn::visitBracketsEmpty(BracketsEmpty *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("[]");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListBracketsOpt(ListBracketsOpt *listbracketsopt)
{
  iterListBracketsOpt(listbracketsopt->begin(), listbracketsopt->end());
}

void PrintAbsyn::iterListBracketsOpt(ListBracketsOpt::const_iterator i, ListBracketsOpt::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); iterListBracketsOpt(i+1, j);
  }
}

void PrintAbsyn::visitListType(ListType *listtype)
{
  iterListType(listtype->begin(), listtype->end());
}

void PrintAbsyn::iterListType(ListType::const_iterator i, ListType::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListType(i+1, j);
  }
}

void PrintAbsyn::visitSBlk(SBlk *p) {} //abstract class

void PrintAbsyn::visitSBlock(SBlock *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('{');
  _i_ = 0; visitListMemdef(p->listmemdef_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitCBlk(CBlk *p) {} //abstract class

void PrintAbsyn::visitCBlock(CBlock *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('{');
  _i_ = 0; visitListCMemdef(p->listcmemdef_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitMemdef(Memdef *p) {} //abstract class

void PrintAbsyn::visitMemberDef(MemberDef *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->type_->accept(this);
  visitIdent(p->ident_);
  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListMemdef(ListMemdef *listmemdef)
{
  iterListMemdef(listmemdef->begin(), listmemdef->end());
}

void PrintAbsyn::iterListMemdef(ListMemdef::const_iterator i, ListMemdef::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); iterListMemdef(i+1, j);
  }
}

void PrintAbsyn::visitCMemdef(CMemdef *p) {} //abstract class

void PrintAbsyn::visitCVarDef(CVarDef *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->memdef_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitCFuncDef(CFuncDef *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->fndef_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListCMemdef(ListCMemdef *listcmemdef)
{
  iterListCMemdef(listcmemdef->begin(), listcmemdef->end());
}

void PrintAbsyn::iterListCMemdef(ListCMemdef::const_iterator i, ListCMemdef::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); iterListCMemdef(i+1, j);
  }
}

void PrintAbsyn::visitBlk(Blk *p) {} //abstract class

void PrintAbsyn::visitBlock(Block *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('{');
  _i_ = 0; visitListStmt(p->liststmt_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListStmt(ListStmt *liststmt)
{
  iterListStmt(liststmt->begin(), liststmt->end());
}

void PrintAbsyn::iterListStmt(ListStmt::const_iterator i, ListStmt::const_iterator j)
{
  if (i == j) return;
  { /* cons */
    (*i)->accept(this); iterListStmt(i+1, j);
  }
}

void PrintAbsyn::visitStmt(Stmt *p) {} //abstract class

void PrintAbsyn::visitEmpty(Empty *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render(';');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBStmt(BStmt *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->blk_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  render(tmp);
}

void PrintAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  render(tmp);
}

void PrintAbsyn::visitChar(Char c)
{
  char tmp[4];
  sprintf(tmp, "'%c'", c);
  render(tmp);
}

void PrintAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
  bufAppend(' ');
}

void PrintAbsyn::visitIdent(String s)
{
  render(s);
}

ShowAbsyn::ShowAbsyn(void)
{
  buf_ = 0;
  bufReset();
}

ShowAbsyn::~ShowAbsyn(void)
{
}

char *ShowAbsyn::show(Visitable *v)
{
  bufReset();
  v->accept(this);
  return buf_;
}

void ShowAbsyn::visitProg(Prog *p) {} //abstract class

void ShowAbsyn::visitProgram(Program *p)
{
  bufAppend('(');
  bufAppend("Program");
  bufAppend(' ');
  bufAppend('[');
  if (p->listtopdef_)  p->listtopdef_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitTopDef(TopDef *p) {} //abstract class

void ShowAbsyn::visitStruct(Struct *p)
{
  bufAppend('(');
  bufAppend("Struct");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->sblk_)  p->sblk_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitTypeDef(TypeDef *p)
{
  bufAppend('(');
  bufAppend("TypeDef");
  bufAppend(' ');
  visitIdent(p->ident_1);
  bufAppend(' ');
  visitIdent(p->ident_2);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitTypeDefWS(TypeDefWS *p)
{
  bufAppend('(');
  bufAppend("TypeDefWS");
  bufAppend(' ');
  visitIdent(p->ident_1);
  bufAppend(' ');
  bufAppend('[');
  if (p->sblk_)  p->sblk_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_2);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitEnum(Enum *p)
{
  bufAppend('(');
  bufAppend("Enum");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->listeval_)  p->listeval_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitClass(Class *p)
{
  bufAppend('(');
  bufAppend("Class");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->cblk_)  p->cblk_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitClassWE(ClassWE *p)
{
  bufAppend('(');
  bufAppend("ClassWE");
  bufAppend(' ');
  visitIdent(p->ident_1);
  bufAppend(' ');
  visitIdent(p->ident_2);
  bufAppend(' ');
  bufAppend('[');
  if (p->cblk_)  p->cblk_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitGFuncDef(GFuncDef *p)
{
  bufAppend('(');
  bufAppend("GFuncDef");
  bufAppend(' ');
  bufAppend('[');
  if (p->fndef_)  p->fndef_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFnDef(FnDef *p) {} //abstract class

void ShowAbsyn::visitFuncDef(FuncDef *p)
{
  bufAppend('(');
  bufAppend("FuncDef");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->listarg_)  p->listarg_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->blk_)  p->blk_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitEVal(EVal *p) {} //abstract class

void ShowAbsyn::visitEnumValue(EnumValue *p)
{
  bufAppend('(');
  bufAppend("EnumValue");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitListEVal(ListEVal *listeval)
{
  for (ListEVal::const_iterator i = listeval->begin() ; i != listeval->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listeval->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitArg(Arg *p) {} //abstract class

void ShowAbsyn::visitArgument(Argument *p)
{
  bufAppend('(');
  bufAppend("Argument");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitListArg(ListArg *listarg)
{
  for (ListArg::const_iterator i = listarg->begin() ; i != listarg->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listarg->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitListTopDef(ListTopDef *listtopdef)
{
  for (ListTopDef::const_iterator i = listtopdef->begin() ; i != listtopdef->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listtopdef->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitType(Type *p) {} //abstract class

void ShowAbsyn::visitInt(Int *p)
{
  bufAppend("Int");
}
void ShowAbsyn::visitDoub(Doub *p)
{
  bufAppend("Doub");
}
void ShowAbsyn::visitBool(Bool *p)
{
  bufAppend("Bool");
}
void ShowAbsyn::visitVoid(Void *p)
{
  bufAppend("Void");
}
void ShowAbsyn::visitObjT(ObjT *p)
{
  bufAppend('(');
  bufAppend("ObjT");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitArray(Array *p)
{
  bufAppend('(');
  bufAppend("Array");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->bracketsopt_)  p->bracketsopt_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitBracketsOpt(BracketsOpt *p) {} //abstract class

void ShowAbsyn::visitBracketsEmpty(BracketsEmpty *p)
{
  bufAppend("BracketsEmpty");
}
void ShowAbsyn::visitListBracketsOpt(ListBracketsOpt *listbracketsopt)
{
  for (ListBracketsOpt::const_iterator i = listbracketsopt->begin() ; i != listbracketsopt->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listbracketsopt->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitListType(ListType *listtype)
{
  for (ListType::const_iterator i = listtype->begin() ; i != listtype->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listtype->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitSBlk(SBlk *p) {} //abstract class

void ShowAbsyn::visitSBlock(SBlock *p)
{
  bufAppend('(');
  bufAppend("SBlock");
  bufAppend(' ');
  bufAppend('[');
  if (p->listmemdef_)  p->listmemdef_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitCBlk(CBlk *p) {} //abstract class

void ShowAbsyn::visitCBlock(CBlock *p)
{
  bufAppend('(');
  bufAppend("CBlock");
  bufAppend(' ');
  bufAppend('[');
  if (p->listcmemdef_)  p->listcmemdef_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitMemdef(Memdef *p) {} //abstract class

void ShowAbsyn::visitMemberDef(MemberDef *p)
{
  bufAppend('(');
  bufAppend("MemberDef");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListMemdef(ListMemdef *listmemdef)
{
  for (ListMemdef::const_iterator i = listmemdef->begin() ; i != listmemdef->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listmemdef->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitCMemdef(CMemdef *p) {} //abstract class

void ShowAbsyn::visitCVarDef(CVarDef *p)
{
  bufAppend('(');
  bufAppend("CVarDef");
  bufAppend(' ');
  bufAppend('[');
  if (p->memdef_)  p->memdef_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitCFuncDef(CFuncDef *p)
{
  bufAppend('(');
  bufAppend("CFuncDef");
  bufAppend(' ');
  bufAppend('[');
  if (p->fndef_)  p->fndef_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListCMemdef(ListCMemdef *listcmemdef)
{
  for (ListCMemdef::const_iterator i = listcmemdef->begin() ; i != listcmemdef->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listcmemdef->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitBlk(Blk *p) {} //abstract class

void ShowAbsyn::visitBlock(Block *p)
{
  bufAppend('(');
  bufAppend("Block");
  bufAppend(' ');
  bufAppend('[');
  if (p->liststmt_)  p->liststmt_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitListStmt(ListStmt *liststmt)
{
  for (ListStmt::const_iterator i = liststmt->begin() ; i != liststmt->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != liststmt->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitStmt(Stmt *p) {} //abstract class

void ShowAbsyn::visitEmpty(Empty *p)
{
  bufAppend("Empty");
}
void ShowAbsyn::visitBStmt(BStmt *p)
{
  bufAppend('(');
  bufAppend("BStmt");
  bufAppend(' ');
  bufAppend('[');
  if (p->blk_)  p->blk_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppend(tmp);
}
void ShowAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppend(tmp);
}
void ShowAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufAppend(c);
  bufAppend('\'');
}
void ShowAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}
void ShowAbsyn::visitIdent(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}


