/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Visitor Design Pattern Skeleton. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "Skeleton.H"



void Skeleton::visitProg(Prog *t) {} //abstract class
void Skeleton::visitTopDef(TopDef *t) {} //abstract class
void Skeleton::visitArg(Arg *t) {} //abstract class
void Skeleton::visitBlk(Blk *t) {} //abstract class
void Skeleton::visitStmt(Stmt *t) {} //abstract class
void Skeleton::visitItem(Item *t) {} //abstract class
void Skeleton::visitSStmt(SStmt *t) {} //abstract class
void Skeleton::visitType(Type *t) {} //abstract class
void Skeleton::visitBracketsOpt(BracketsOpt *t) {} //abstract class
void Skeleton::visitExpr(Expr *t) {} //abstract class
void Skeleton::visitDimExpr(DimExpr *t) {} //abstract class
void Skeleton::visitAddOp(AddOp *t) {} //abstract class
void Skeleton::visitMulOp(MulOp *t) {} //abstract class
void Skeleton::visitRelOp(RelOp *t) {} //abstract class
void Skeleton::visitMAccOp(MAccOp *t) {} //abstract class

void Skeleton::visitProgram(Program *program)
{
  /* Code For Program Goes Here */

  if (program->listtopdef_) program->listtopdef_->accept(this);

}

void Skeleton::visitTypeDef(TypeDef *type_def)
{
  /* Code For TypeDef Goes Here */

  visitIdent(type_def->ident_1);
  visitIdent(type_def->ident_2);

}

void Skeleton::visitStructDef(StructDef *struct_def)
{
  /* Code For StructDef Goes Here */

  visitIdent(struct_def->ident_);
  if (struct_def->listsstmt_) struct_def->listsstmt_->accept(this);

}

void Skeleton::visitFnDef(FnDef *fn_def)
{
  /* Code For FnDef Goes Here */

  if (fn_def->type_) fn_def->type_->accept(this);
  visitIdent(fn_def->ident_);
  if (fn_def->listarg_) fn_def->listarg_->accept(this);
  if (fn_def->blk_) fn_def->blk_->accept(this);

}

void Skeleton::visitFnDefS(FnDefS *fn_def_s)
{
  /* Code For FnDefS Goes Here */

  visitIdent(fn_def_s->ident_1);
  visitIdent(fn_def_s->ident_2);
  if (fn_def_s->listarg_) fn_def_s->listarg_->accept(this);
  if (fn_def_s->blk_) fn_def_s->blk_->accept(this);

}

void Skeleton::visitArgument(Argument *argument)
{
  /* Code For Argument Goes Here */

  if (argument->type_) argument->type_->accept(this);
  visitIdent(argument->ident_);

}

void Skeleton::visitPtrgument(Ptrgument *ptrgument)
{
  /* Code For Ptrgument Goes Here */

  visitIdent(ptrgument->ident_1);
  visitIdent(ptrgument->ident_2);

}

void Skeleton::visitBlock(Block *block)
{
  /* Code For Block Goes Here */

  if (block->liststmt_) block->liststmt_->accept(this);

}

void Skeleton::visitEmpty(Empty *empty)
{
  /* Code For Empty Goes Here */


}

void Skeleton::visitBStmt(BStmt *b_stmt)
{
  /* Code For BStmt Goes Here */

  if (b_stmt->blk_) b_stmt->blk_->accept(this);

}

void Skeleton::visitDecl(Decl *decl)
{
  /* Code For Decl Goes Here */

  if (decl->type_) decl->type_->accept(this);
  if (decl->listitem_) decl->listitem_->accept(this);

}

void Skeleton::visitDeclStruct(DeclStruct *decl_struct)
{
  /* Code For DeclStruct Goes Here */

  visitIdent(decl_struct->ident_);
  if (decl_struct->listitem_) decl_struct->listitem_->accept(this);

}

void Skeleton::visitAss(Ass *ass)
{
  /* Code For Ass Goes Here */

  visitIdent(ass->ident_);
  if (ass->expr_) ass->expr_->accept(this);

}

void Skeleton::visitAssArr(AssArr *ass_arr)
{
  /* Code For AssArr Goes Here */

  if (ass_arr->expr_1) ass_arr->expr_1->accept(this);
  if (ass_arr->expr_2) ass_arr->expr_2->accept(this);

}

void Skeleton::visitIncr(Incr *incr)
{
  /* Code For Incr Goes Here */

  visitIdent(incr->ident_);

}

void Skeleton::visitDecr(Decr *decr)
{
  /* Code For Decr Goes Here */

  visitIdent(decr->ident_);

}

void Skeleton::visitRet(Ret *ret)
{
  /* Code For Ret Goes Here */

  if (ret->expr_) ret->expr_->accept(this);

}

void Skeleton::visitVRet(VRet *v_ret)
{
  /* Code For VRet Goes Here */


}

void Skeleton::visitCond(Cond *cond)
{
  /* Code For Cond Goes Here */

  if (cond->expr_) cond->expr_->accept(this);
  if (cond->stmt_) cond->stmt_->accept(this);

}

void Skeleton::visitCondElse(CondElse *cond_else)
{
  /* Code For CondElse Goes Here */

  if (cond_else->expr_) cond_else->expr_->accept(this);
  if (cond_else->stmt_1) cond_else->stmt_1->accept(this);
  if (cond_else->stmt_2) cond_else->stmt_2->accept(this);

}

void Skeleton::visitWhile(While *while_)
{
  /* Code For While Goes Here */

  if (while_->expr_) while_->expr_->accept(this);
  if (while_->stmt_) while_->stmt_->accept(this);

}

void Skeleton::visitForLoop(ForLoop *for_loop)
{
  /* Code For ForLoop Goes Here */

  if (for_loop->type_) for_loop->type_->accept(this);
  visitIdent(for_loop->ident_);
  if (for_loop->expr_) for_loop->expr_->accept(this);
  if (for_loop->stmt_) for_loop->stmt_->accept(this);

}

void Skeleton::visitForStruct(ForStruct *for_struct)
{
  /* Code For ForStruct Goes Here */

  visitIdent(for_struct->ident_1);
  visitIdent(for_struct->ident_2);
  if (for_struct->expr_) for_struct->expr_->accept(this);
  if (for_struct->stmt_) for_struct->stmt_->accept(this);

}

void Skeleton::visitSExp(SExp *s_exp)
{
  /* Code For SExp Goes Here */

  if (s_exp->expr_) s_exp->expr_->accept(this);

}

void Skeleton::visitNoInit(NoInit *no_init)
{
  /* Code For NoInit Goes Here */

  visitIdent(no_init->ident_);

}

void Skeleton::visitInit(Init *init)
{
  /* Code For Init Goes Here */

  visitIdent(init->ident_);
  if (init->expr_) init->expr_->accept(this);

}

void Skeleton::visitMInner(MInner *m_inner)
{
  /* Code For MInner Goes Here */

  if (m_inner->type_) m_inner->type_->accept(this);
  visitIdent(m_inner->ident_);

}

void Skeleton::visitMArray(MArray *m_array)
{
  /* Code For MArray Goes Here */

  if (m_array->type_) m_array->type_->accept(this);
  if (m_array->listbracketsopt_) m_array->listbracketsopt_->accept(this);
  visitIdent(m_array->ident_);

}

void Skeleton::visitMSArray(MSArray *ms_array)
{
  /* Code For MSArray Goes Here */

  visitIdent(ms_array->ident_1);
  if (ms_array->listbracketsopt_) ms_array->listbracketsopt_->accept(this);
  visitIdent(ms_array->ident_2);

}

void Skeleton::visitMStruct(MStruct *m_struct)
{
  /* Code For MStruct Goes Here */

  visitIdent(m_struct->ident_1);
  visitIdent(m_struct->ident_2);

}

void Skeleton::visitInt(Int *int_)
{
  /* Code For Int Goes Here */


}

void Skeleton::visitDoub(Doub *doub)
{
  /* Code For Doub Goes Here */


}

void Skeleton::visitBool(Bool *bool_)
{
  /* Code For Bool Goes Here */


}

void Skeleton::visitVoid(Void *void_)
{
  /* Code For Void Goes Here */


}

void Skeleton::visitFun(Fun *fun)
{
  /* Code For Fun Goes Here */

  if (fun->type_) fun->type_->accept(this);
  if (fun->listtype_) fun->listtype_->accept(this);

}

void Skeleton::visitArrayType(ArrayType *array_type)
{
  /* Code For ArrayType Goes Here */

  if (array_type->type_) array_type->type_->accept(this);
  if (array_type->listbracketsopt_) array_type->listbracketsopt_->accept(this);

}

void Skeleton::visitSArrayType(SArrayType *s_array_type)
{
  /* Code For SArrayType Goes Here */

  visitIdent(s_array_type->ident_);
  if (s_array_type->listbracketsopt_) s_array_type->listbracketsopt_->accept(this);

}

void Skeleton::visitBracketsEmpty(BracketsEmpty *brackets_empty)
{
  /* Code For BracketsEmpty Goes Here */


}

void Skeleton::visitENewArray(ENewArray *e_new_array)
{
  /* Code For ENewArray Goes Here */

  if (e_new_array->type_) e_new_array->type_->accept(this);
  if (e_new_array->listdimexpr_) e_new_array->listdimexpr_->accept(this);

}

void Skeleton::visitENewSArray(ENewSArray *e_new_s_array)
{
  /* Code For ENewSArray Goes Here */

  visitIdent(e_new_s_array->ident_);
  if (e_new_s_array->listdimexpr_) e_new_s_array->listdimexpr_->accept(this);

}

void Skeleton::visitEDot(EDot *e_dot)
{
  /* Code For EDot Goes Here */

  if (e_dot->expr_) e_dot->expr_->accept(this);
  visitIdent(e_dot->ident_);

}

void Skeleton::visitEAcc(EAcc *e_acc)
{
  /* Code For EAcc Goes Here */

  if (e_acc->expr_) e_acc->expr_->accept(this);
  if (e_acc->listdimexpr_) e_acc->listdimexpr_->accept(this);

}

void Skeleton::visitENewStruct(ENewStruct *e_new_struct)
{
  /* Code For ENewStruct Goes Here */

  visitIdent(e_new_struct->ident_);

}

void Skeleton::visitEMember(EMember *e_member)
{
  /* Code For EMember Goes Here */

  if (e_member->expr_) e_member->expr_->accept(this);
  if (e_member->maccop_) e_member->maccop_->accept(this);
  visitIdent(e_member->ident_);

}

void Skeleton::visitTypeCast(TypeCast *type_cast)
{
  /* Code For TypeCast Goes Here */

  visitIdent(type_cast->ident_);

}

void Skeleton::visitELitInt(ELitInt *e_lit_int)
{
  /* Code For ELitInt Goes Here */

  visitInteger(e_lit_int->integer_);

}

void Skeleton::visitELitDoub(ELitDoub *e_lit_doub)
{
  /* Code For ELitDoub Goes Here */

  visitDouble(e_lit_doub->double_);

}

void Skeleton::visitELitTrue(ELitTrue *e_lit_true)
{
  /* Code For ELitTrue Goes Here */


}

void Skeleton::visitELitFalse(ELitFalse *e_lit_false)
{
  /* Code For ELitFalse Goes Here */


}

void Skeleton::visitEString(EString *e_string)
{
  /* Code For EString Goes Here */

  visitString(e_string->string_);

}

void Skeleton::visitEVar(EVar *e_var)
{
  /* Code For EVar Goes Here */

  visitIdent(e_var->ident_);

}

void Skeleton::visitEApp(EApp *e_app)
{
  /* Code For EApp Goes Here */

  visitIdent(e_app->ident_);
  if (e_app->listexpr_) e_app->listexpr_->accept(this);

}

void Skeleton::visitNeg(Neg *neg)
{
  /* Code For Neg Goes Here */

  if (neg->expr_) neg->expr_->accept(this);

}

void Skeleton::visitNot(Not *not_)
{
  /* Code For Not Goes Here */

  if (not_->expr_) not_->expr_->accept(this);

}

void Skeleton::visitEMul(EMul *e_mul)
{
  /* Code For EMul Goes Here */

  if (e_mul->expr_1) e_mul->expr_1->accept(this);
  if (e_mul->mulop_) e_mul->mulop_->accept(this);
  if (e_mul->expr_2) e_mul->expr_2->accept(this);

}

void Skeleton::visitEAdd(EAdd *e_add)
{
  /* Code For EAdd Goes Here */

  if (e_add->expr_1) e_add->expr_1->accept(this);
  if (e_add->addop_) e_add->addop_->accept(this);
  if (e_add->expr_2) e_add->expr_2->accept(this);

}

void Skeleton::visitERel(ERel *e_rel)
{
  /* Code For ERel Goes Here */

  if (e_rel->expr_1) e_rel->expr_1->accept(this);
  if (e_rel->relop_) e_rel->relop_->accept(this);
  if (e_rel->expr_2) e_rel->expr_2->accept(this);

}

void Skeleton::visitEAnd(EAnd *e_and)
{
  /* Code For EAnd Goes Here */

  if (e_and->expr_1) e_and->expr_1->accept(this);
  if (e_and->expr_2) e_and->expr_2->accept(this);

}

void Skeleton::visitEOr(EOr *e_or)
{
  /* Code For EOr Goes Here */

  if (e_or->expr_1) e_or->expr_1->accept(this);
  if (e_or->expr_2) e_or->expr_2->accept(this);

}

void Skeleton::visitDim(Dim *dim)
{
  /* Code For Dim Goes Here */

  if (dim->expr_) dim->expr_->accept(this);

}

void Skeleton::visitPlus(Plus *plus)
{
  /* Code For Plus Goes Here */


}

void Skeleton::visitMinus(Minus *minus)
{
  /* Code For Minus Goes Here */


}

void Skeleton::visitTimes(Times *times)
{
  /* Code For Times Goes Here */


}

void Skeleton::visitDiv(Div *div)
{
  /* Code For Div Goes Here */


}

void Skeleton::visitMod(Mod *mod)
{
  /* Code For Mod Goes Here */


}

void Skeleton::visitLTH(LTH *lth)
{
  /* Code For LTH Goes Here */


}

void Skeleton::visitLE(LE *le)
{
  /* Code For LE Goes Here */


}

void Skeleton::visitGTH(GTH *gth)
{
  /* Code For GTH Goes Here */


}

void Skeleton::visitGE(GE *ge)
{
  /* Code For GE Goes Here */


}

void Skeleton::visitEQU(EQU *equ)
{
  /* Code For EQU Goes Here */


}

void Skeleton::visitNE(NE *ne)
{
  /* Code For NE Goes Here */


}

void Skeleton::visitMAcc(MAcc *m_acc)
{
  /* Code For MAcc Goes Here */


}


void Skeleton::visitListTopDef(ListTopDef *list_top_def)
{
  for (ListTopDef::iterator i = list_top_def->begin() ; i != list_top_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListArg(ListArg *list_arg)
{
  for (ListArg::iterator i = list_arg->begin() ; i != list_arg->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListStmt(ListStmt *list_stmt)
{
  for (ListStmt::iterator i = list_stmt->begin() ; i != list_stmt->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListItem(ListItem *list_item)
{
  for (ListItem::iterator i = list_item->begin() ; i != list_item->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListSStmt(ListSStmt *list_s_stmt)
{
  for (ListSStmt::iterator i = list_s_stmt->begin() ; i != list_s_stmt->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListType(ListType *list_type)
{
  for (ListType::iterator i = list_type->begin() ; i != list_type->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListBracketsOpt(ListBracketsOpt *list_brackets_opt)
{
  for (ListBracketsOpt::iterator i = list_brackets_opt->begin() ; i != list_brackets_opt->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListDimExpr(ListDimExpr *list_dim_expr)
{
  for (ListDimExpr::iterator i = list_dim_expr->begin() ; i != list_dim_expr->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListExpr(ListExpr *list_expr)
{
  for (ListExpr::iterator i = list_expr->begin() ; i != list_expr->end() ; ++i)
  {
    (*i)->accept(this);
  }
}


void Skeleton::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void Skeleton::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void Skeleton::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void Skeleton::visitString(String x)
{
  /* Code for String Goes Here */
}

void Skeleton::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}



