/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Visitor Design Pattern Skeleton. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "Skeleton.H"



void Skeleton::visitProg(Prog *t) {} //abstract class
void Skeleton::visitTopDef(TopDef *t) {} //abstract class
void Skeleton::visitFnDef(FnDef *t) {} //abstract class
void Skeleton::visitEVal(EVal *t) {} //abstract class
void Skeleton::visitArg(Arg *t) {} //abstract class
void Skeleton::visitType(Type *t) {} //abstract class
void Skeleton::visitBracketsOpt(BracketsOpt *t) {} //abstract class
void Skeleton::visitSBlk(SBlk *t) {} //abstract class
void Skeleton::visitCBlk(CBlk *t) {} //abstract class
void Skeleton::visitMemdef(Memdef *t) {} //abstract class
void Skeleton::visitCMemdef(CMemdef *t) {} //abstract class
void Skeleton::visitBlk(Blk *t) {} //abstract class
void Skeleton::visitStmt(Stmt *t) {} //abstract class

void Skeleton::visitProgram(Program *program)
{
  /* Code For Program Goes Here */

  if (program->listtopdef_) program->listtopdef_->accept(this);

}

void Skeleton::visitStruct(Struct *struct_)
{
  /* Code For Struct Goes Here */

  visitIdent(struct_->ident_);
  if (struct_->sblk_) struct_->sblk_->accept(this);

}

void Skeleton::visitTypeDef(TypeDef *type_def)
{
  /* Code For TypeDef Goes Here */

  visitIdent(type_def->ident_1);
  visitIdent(type_def->ident_2);

}

void Skeleton::visitTypeDefWS(TypeDefWS *type_def_ws)
{
  /* Code For TypeDefWS Goes Here */

  visitIdent(type_def_ws->ident_1);
  if (type_def_ws->sblk_) type_def_ws->sblk_->accept(this);
  visitIdent(type_def_ws->ident_2);

}

void Skeleton::visitEnum(Enum *enum_)
{
  /* Code For Enum Goes Here */

  visitIdent(enum_->ident_);
  if (enum_->listeval_) enum_->listeval_->accept(this);

}

void Skeleton::visitClass(Class *class_)
{
  /* Code For Class Goes Here */

  visitIdent(class_->ident_);
  if (class_->cblk_) class_->cblk_->accept(this);

}

void Skeleton::visitClassWE(ClassWE *class_we)
{
  /* Code For ClassWE Goes Here */

  visitIdent(class_we->ident_1);
  visitIdent(class_we->ident_2);
  if (class_we->cblk_) class_we->cblk_->accept(this);

}

void Skeleton::visitGFuncDef(GFuncDef *g_func_def)
{
  /* Code For GFuncDef Goes Here */

  if (g_func_def->fndef_) g_func_def->fndef_->accept(this);

}

void Skeleton::visitFuncDef(FuncDef *func_def)
{
  /* Code For FuncDef Goes Here */

  if (func_def->type_) func_def->type_->accept(this);
  visitIdent(func_def->ident_);
  if (func_def->listarg_) func_def->listarg_->accept(this);
  if (func_def->blk_) func_def->blk_->accept(this);

}

void Skeleton::visitEnumValue(EnumValue *enum_value)
{
  /* Code For EnumValue Goes Here */

  visitIdent(enum_value->ident_);

}

void Skeleton::visitArgument(Argument *argument)
{
  /* Code For Argument Goes Here */

  if (argument->type_) argument->type_->accept(this);
  visitIdent(argument->ident_);

}

void Skeleton::visitInt(Int *int_)
{
  /* Code For Int Goes Here */


}

void Skeleton::visitDoub(Doub *doub)
{
  /* Code For Doub Goes Here */


}

void Skeleton::visitBool(Bool *bool_)
{
  /* Code For Bool Goes Here */


}

void Skeleton::visitVoid(Void *void_)
{
  /* Code For Void Goes Here */


}

void Skeleton::visitObjT(ObjT *obj_t)
{
  /* Code For ObjT Goes Here */

  visitIdent(obj_t->ident_);

}

void Skeleton::visitArray(Array *array)
{
  /* Code For Array Goes Here */

  if (array->type_) array->type_->accept(this);
  if (array->bracketsopt_) array->bracketsopt_->accept(this);

}

void Skeleton::visitBracketsEmpty(BracketsEmpty *brackets_empty)
{
  /* Code For BracketsEmpty Goes Here */


}

void Skeleton::visitSBlock(SBlock *s_block)
{
  /* Code For SBlock Goes Here */

  if (s_block->listmemdef_) s_block->listmemdef_->accept(this);

}

void Skeleton::visitCBlock(CBlock *c_block)
{
  /* Code For CBlock Goes Here */

  if (c_block->listcmemdef_) c_block->listcmemdef_->accept(this);

}

void Skeleton::visitMemberDef(MemberDef *member_def)
{
  /* Code For MemberDef Goes Here */

  if (member_def->type_) member_def->type_->accept(this);
  visitIdent(member_def->ident_);

}

void Skeleton::visitCVarDef(CVarDef *c_var_def)
{
  /* Code For CVarDef Goes Here */

  if (c_var_def->memdef_) c_var_def->memdef_->accept(this);

}

void Skeleton::visitCFuncDef(CFuncDef *c_func_def)
{
  /* Code For CFuncDef Goes Here */

  if (c_func_def->fndef_) c_func_def->fndef_->accept(this);

}

void Skeleton::visitBlock(Block *block)
{
  /* Code For Block Goes Here */

  if (block->liststmt_) block->liststmt_->accept(this);

}

void Skeleton::visitEmpty(Empty *empty)
{
  /* Code For Empty Goes Here */


}

void Skeleton::visitBStmt(BStmt *b_stmt)
{
  /* Code For BStmt Goes Here */

  if (b_stmt->blk_) b_stmt->blk_->accept(this);

}


void Skeleton::visitListEVal(ListEVal *list_e_val)
{
  for (ListEVal::iterator i = list_e_val->begin() ; i != list_e_val->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListArg(ListArg *list_arg)
{
  for (ListArg::iterator i = list_arg->begin() ; i != list_arg->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListTopDef(ListTopDef *list_top_def)
{
  for (ListTopDef::iterator i = list_top_def->begin() ; i != list_top_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListBracketsOpt(ListBracketsOpt *list_brackets_opt)
{
  for (ListBracketsOpt::iterator i = list_brackets_opt->begin() ; i != list_brackets_opt->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListType(ListType *list_type)
{
  for (ListType::iterator i = list_type->begin() ; i != list_type->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListMemdef(ListMemdef *list_memdef)
{
  for (ListMemdef::iterator i = list_memdef->begin() ; i != list_memdef->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListCMemdef(ListCMemdef *list_c_memdef)
{
  for (ListCMemdef::iterator i = list_c_memdef->begin() ; i != list_c_memdef->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListStmt(ListStmt *list_stmt)
{
  for (ListStmt::iterator i = list_stmt->begin() ; i != list_stmt->end() ; ++i)
  {
    (*i)->accept(this);
  }
}


void Skeleton::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void Skeleton::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void Skeleton::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void Skeleton::visitString(String x)
{
  /* Code for String Goes Here */
}

void Skeleton::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}



